charter/urls.py
# ope -- stands for "Outil de Préparation à l'Évaluation" in french
# Copyright 2015 ope contributors.  See AUTHORS.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import \
    include, \
    url
from django.contrib import \
    admin
from django.utils.translation import \
    ugettext_lazy as _
from django.views.generic import \
    TemplateView


urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name="home.html"),
        name="home"),
    url(r'^admin/',
        admin.site.urls),


    url(_(r'^history/'),
        include('job.urls.history')),
    url(_(r'^person/'),
        include('job.urls.person')),
    url(_(r'^job/'),
        include('job.urls.job')),

    url(_(r'^partner/'),
        include('partner.urls')),

    url(_(r'^node/'),
        include('state.urls')),
]

partner/urls.py
# ope -- stands for "Outil de Préparation à l'Évaluation" in french
# Copyright 2015 ope contributors.  See AUTHORS.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import \
    url
from django.utils.translation import \
    ugettext_lazy as _
from partner.views import \
    PartnerList, \
    PartnerAdd, \
    PartnerSee, \
    PartnerEdit, \
    PartnerDrop


app_name = 'partner'

urlpatterns = [
    url(_(r'^list/$'),
        PartnerList.as_view(),
        name='list'),
    url(_(r'^add/$'),
        PartnerAdd.as_view(),
        name='add'),
    url(r'^(?P<pk>\d+)/see/$',
        PartnerSee.as_view(),
        name='see'),
    url(_(r'^(?P<pk>\d+)/edit/$'),
        PartnerEdit.as_view(),
        name='edit'),
    url(_(r'^(?P<pk>\d+)/drop/$'),
        PartnerDrop.as_view(),
        name='drop'),
]

state/urls.py
# ope -- stands for "Outil de Préparation à l'Évaluation" in french
# Copyright 2015 ope contributors.  See AUTHORS.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import \
    include, \
    url
from django.utils.translation import \
    ugettext_lazy as _
from state.views.identity import \
    IndicatorAdd, IndicatorEdit, IndicatorDrop, \
    IdentityAdd, IdentityEdit
from state.views.state import \
    AccountLineAdd, AccountLineEdit, AccountLineDrop, \
    ExtensionAdd, ExtensionEdit, ExtensionDrop, \
    FundingAdd, FundingEdit, FundingDrop, \
    HumanMeanAdd, HumanMeanEdit, HumanMeanDrop, \
    PartnershipAdd, PartnershipEdit, PartnershipDrop, \
    ResultAdd, ResultEdit, ResultDrop, \
    StateAdd, StateSee, StateEdit, StateExport, \
    StepAdd, StepEdit, StepDrop, \
    StateTechFile
from state.views.tree import \
    NodeAdd, NodeSee, NodeEdit


app_name = 'node'

aline_urlpatterns = ([
    url(_(r'^add/$'),
        AccountLineAdd.as_view(), name='add'),
    url(_(r'^(?P<aline_pk>\d+)/edit/$'),
        AccountLineEdit.as_view(), name='edit'),
    url(_(r'^(?P<aline_pk>\d+)/drop/$'),
        AccountLineDrop.as_view(), name='drop'),
], 'accountline')

extension_urlpatterns = ([
    url(_(r'^add/$'),
        ExtensionAdd.as_view(), name='add'),
    url(_(r'^(?P<ext_pk>\d+)/edit/$'),
        ExtensionEdit.as_view(), name='edit'),
    url(_(r'^(?P<ext_pk>\d+)/drop/$'),
        ExtensionDrop.as_view(), name='drop'),
], 'extension')

funding_urlpatterns = ([
    url(_(r'^add/$'),
        FundingAdd.as_view(), name='add'),
    url(_(r'^(?P<fund_pk>\d+)/edit/$'),
        FundingEdit.as_view(), name='edit'),
    url(_(r'^(?P<fund_pk>\d+)/drop/$'),
        FundingDrop.as_view(), name='drop'),
], 'funding')

hmean_urlpatterns = ([
    url(_(r'^add/$'),
        HumanMeanAdd.as_view(), name='add'),
    url(_(r'^(?P<hmean_pk>\d+)/edit/$'),
        HumanMeanEdit.as_view(), name='edit'),
    url(_(r'^(?P<hmean_pk>\d+)/drop/$'),
        HumanMeanDrop.as_view(), name='drop'),
], 'humanmean')

pship_urlpatterns = ([
    url(_(r'^add/$'),
        PartnershipAdd.as_view(), name='add'),
    url(_(r'^(?P<pship_pk>\d+)/edit/$'),
        PartnershipEdit.as_view(), name='edit'),
    url(_(r'^(?P<pship_pk>\d+)/drop/$'),
        PartnershipDrop.as_view(), name='drop'),
], 'partnership')

result_urlpatterns = ([
    url(_(r'^add/$'),
        ResultAdd.as_view(), name='add'),
    url(_(r'^(?P<result_pk>\d+)/edit/$'),
        ResultEdit.as_view(), name='edit'),
    url(_(r'^(?P<result_pk>\d+)/drop/$'),
        ResultDrop.as_view(), name='drop'),
], 'result')

step_urlpatterns = ([
    url(_(r'^add/$'),
        StepAdd.as_view(), name='add'),
    url(_(r'^(?P<step_pk>\d+)/edit/$'),
        StepEdit.as_view(), name='edit'),
    url(_(r'^(?P<step_pk>\d+)/drop/$'),
        StepDrop.as_view(), name='drop'),
], 'step')

state_urlpatterns = ([
    url(_(r'^add/\?type_id=(?P<type_id>\d+)/$'),
        StateAdd.as_view(), name='add'),
    url(_(r'^(?P<state_pk>\d+)/see/$'),
        StateSee.as_view(), name='see'),
    url(_(r'^(?P<state_pk>\d+)/edit/$'),
        StateEdit.as_view(), name='edit'),
    url(_(r'^(?P<state_pk>\d+)/techfile/$'),
        StateTechFile.as_view(), name='techfile'),
    url(_(r'^(?P<state_pk>\d+)/export/$'),
        StateExport.as_view(), name='export'),
    # url(_(r'^(?P<state_pk>\d+)/exportpdf/$'),
    #     StateExportPdf, name='exportpdf'),
    url(_(r'^(?P<state_pk>\d+)/accountline/'),
        include(aline_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/extension/'),
        include(extension_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/funding/'),
        include(funding_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/humanmean/'),
        include(hmean_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/partnership/'),
        include(pship_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/result/'),
        include(result_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/step/'),
        include(step_urlpatterns)),
], 'state')

indicator_urlpatterns = ([
    url(_(r'^add/$'),
        IndicatorAdd.as_view(), name='add'),
    url(_(r'^(?P<indi_pk>\d+)/edit/$'),
        IndicatorEdit.as_view(), name='edit'),
    url(_(r'^(?P<indi_pk>\d+)/drop/$'),
        IndicatorDrop.as_view(), name='drop'),
], 'indi')

identity_urlpatterns = ([
    url(_(r'^add/$'),
        IdentityAdd.as_view(), name='add'),
    url(_(r'^(?P<iden_pk>\d+)/edit/$'),
        IdentityEdit.as_view(), name='edit'),
    url(_(r'^(?P<iden_pk>\d+)/indicator/'),
        include(indicator_urlpatterns)),
    url(_(r'^(?P<iden_pk>\d+)/state/'),
        include(state_urlpatterns)),
], 'iden')

urlpatterns = [
    url(_(r'^(?P<node_pk>\d+)/add/$'),
        NodeAdd.as_view(), name='add'),
    url(_(r'^(?P<node_pk>\d+)/see/$'),
        NodeSee.as_view(), name='see'),
    url(_(r'^(?P<node_pk>\d+)/edit/$'),
        NodeEdit.as_view(), name='edit'),
    url(_(r'^(?P<node_pk>\d+)/identity/'),
        include(identity_urlpatterns)),
]

charter/templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible"
        content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet"
        href="{% static "bootstrap-3.3.6-dist/css/bootstrap.min.css" %}">
  <link rel="stylesheet"
        href="{% static "bootstrap-3.3.6-dist/css/bootstrap-theme.min.css" %}">
  <!--
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
  -->
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">

      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button"
                class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand"
           href="{% url 'home' %}">Adamo</a>
      </div><!-- /.navbar-header -->

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse"
           id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <a href="{% url 'node:see' 1 %}">
              Charte Objectif 2025
            </a>
          </li>
          <li>
            <a href="{% url 'partner:list' %}">
              {% trans "partner"|capfirst %}
            </a>
          </li>
          <li>
            <a href="{% url 'admin:index' %}">
              Administration
            </a>
          </li>
        </ul>
        {% block bar %}{% endblock %}
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>

  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <script src="{% static "jquery.min.js" %}">
  </script>
  <script src="{% static "bootstrap-3.3.6-dist/js/bootstrap.min.js" %}">
  </script>
  <!--
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
  </script>-->
</body>
</html>

charter/templates/drop.html
{% extends "base.html" %}
{% load i18n %}

{% trans "droping"|capfirst as title_2nd %}
{% block title %}{{ title_2nd }} {{ object }}{% endblock %}

{% block content %}
  {% include "top.html" with h2=object small=title_2nd %}
    <div class="alert alert-warning" role="alert">
      <form action="" method="post">{% csrf_token %}
        <p>{% trans "drop element"|capfirst %}
          <em><strong>'{{ object }}'</strong></em> ?</p>
        <button type="submit"
                class="btn btn-danger"
                name="button">
          <span class="glyphicon glyphicon-ok"
                aria-hidden="true"></span>
          {% trans "confirm"|capfirst %}</button>
        <a class="btn btn-success"
           href="{{ view.get_success_url }}"
           role="button">
          <span class="glyphicon glyphicon-remove"
                aria-hidden="true"></span>
          {% trans "cancel"|capfirst %}</a>
      </form>
    </div>
{% endblock %}

charter/templates/form.html
{% extends "base.html" %}
{% load utils_filters %}

{% block title %}{{ view|verbose_name|capfirst }}{% endblock %}

{% block content %}
  {% include "top.html" with h2=view|verbose_name|capfirst small=object|add_or_edit_str|capfirst %}
  {% load crispy_forms_tags %}
  {% crispy form %}
{% endblock %}

charter/templates/home.html
{% extends "base.html" %}

{% block title %}Adamo{% endblock %}

{% block content %}
    <div class="page-header">
      <div class="jumbotron">
        <h1>Adamo
          <small>
            Outil de Préparation à l'Évaluation de la Charte
          </small>
        </h1>
      </div>
    </div>
{% endblock %}

charter/templates/list.html
{% extends "base.html" %}
{% load i18n %}
{% load utils_filters %}

{% block title %}{{ view|verbose_name_plural|capfirst }}
{% endblock %}

{% block content %}
{% with title_1st=view|verbose_name_plural|capfirst %}
{% trans "List" as title_2nd %}
{% include "top.html" with h2=title_1st small=title_2nd %}
{% endwith %}
    {% if object_list %}
      {% if is_paginated %}
      <div class="text-center">
        <ul class="pagination">
          {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}"
                 aria-label={% trans "Previous" %}>
          {% else %}
          <li class="disabled"><a aria-label={% trans "Previous" %}>
          {% endif %}
            <span class="glyphicon glyphicon-chevron-left"
                  aria-hidden="true"></span></a></li>

          {% for p in paginator.page_range %}
          {% if p == page_obj.number %}
          <li class="active"><a>
          {% else %}
          <li><a href="?page={{ p }}">
          {% endif %}
            {{ p }}</a></li>
          {% endfor %}

          {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}"
                 aria-label={% trans "Next" %}>
          {% else %}
          <li class="disabled"><a aria-label={% trans "Next" %}>
          {% endif %}
            <span class="glyphicon glyphicon-chevron-right"
                  aria-hidden="true"></span></a></li>
        </ul>
      </div>
      {% endif %}
      <table class="table table-condensed table-striped">
        <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{ object }}</td>
            <td>
              <a href="{% url object|see_url object.id %}"
                 data-toggle="tooltip"
                 title={% trans "see"|capfirst %}>
                <span class="glyphicon glyphicon-eye-open"
                      aria-hidden="true"></span></a></td>
            <td>
              <a href="{% url object|edit_url object.id %}"
                 data-toggle="tooltip"
                 title={% trans "edit"|capfirst %}>
                <span class="glyphicon glyphicon-pencil"
                      aria-hidden="true"></span></a></td>
            <td>
              <a href="{% url object|drop_url object.id %}"
                 data-toggle="tooltip"
                 title={% trans "drop"|capfirst %}>
                <span class="glyphicon glyphicon-remove"
                      aria-hidden="true"></span></a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>
        {% trans "The list is empty." %}
        {% trans "You should use the following add functionnality." %}
      </p>
    {% endif %}
      <div>
        <p class="text-center">
          <a href="{% url view|add_url_fqn %}">
            <span class="glyphicon glyphicon-plus"
                  aria-hidden="true"></span>
            <strong>{% trans "add" %}</strong></a></p>
      </div>
{% endblock %}

charter/templates/top.html
    <div class="page-header">
      <h2>
        {{ h2 }}
        <small>{{ small }}</small>
      </h2>
    </div>