state/urls.py
# ope -- stands for "Outil de Préparation à l'Évaluation" in french
# Copyright 2015 ope contributors.  See AUTHORS.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import \
    include, \
    url
from django.utils.translation import \
    ugettext_lazy as _
from state.views.identity import \
    IndicatorAdd, IndicatorEdit, IndicatorDrop, \
    IdentityAdd, IdentityEdit
from state.views.state import \
    AccountLineAdd, AccountLineEdit, AccountLineDrop, \
    ExtensionAdd, ExtensionEdit, ExtensionDrop, \
    FundingAdd, FundingEdit, FundingDrop, \
    HumanMeanAdd, HumanMeanEdit, HumanMeanDrop, \
    PartnershipAdd, PartnershipEdit, PartnershipDrop, \
    ResultAdd, ResultEdit, ResultDrop, \
    StateAdd, StateSee, StateEdit, StateExport, \
    StepAdd, StepEdit, StepDrop, \
    StateTechFile
from state.views.tree import \
    NodeAdd, NodeSee, NodeEdit


app_name = 'node'

aline_urlpatterns = ([
    url(_(r'^add/$'),
        AccountLineAdd.as_view(), name='add'),
    url(_(r'^(?P<aline_pk>\d+)/edit/$'),
        AccountLineEdit.as_view(), name='edit'),
    url(_(r'^(?P<aline_pk>\d+)/drop/$'),
        AccountLineDrop.as_view(), name='drop'),
], 'accountline')

extension_urlpatterns = ([
    url(_(r'^add/$'),
        ExtensionAdd.as_view(), name='add'),
    url(_(r'^(?P<ext_pk>\d+)/edit/$'),
        ExtensionEdit.as_view(), name='edit'),
    url(_(r'^(?P<ext_pk>\d+)/drop/$'),
        ExtensionDrop.as_view(), name='drop'),
], 'extension')

funding_urlpatterns = ([
    url(_(r'^add/$'),
        FundingAdd.as_view(), name='add'),
    url(_(r'^(?P<fund_pk>\d+)/edit/$'),
        FundingEdit.as_view(), name='edit'),
    url(_(r'^(?P<fund_pk>\d+)/drop/$'),
        FundingDrop.as_view(), name='drop'),
], 'funding')

hmean_urlpatterns = ([
    url(_(r'^add/$'),
        HumanMeanAdd.as_view(), name='add'),
    url(_(r'^(?P<hmean_pk>\d+)/edit/$'),
        HumanMeanEdit.as_view(), name='edit'),
    url(_(r'^(?P<hmean_pk>\d+)/drop/$'),
        HumanMeanDrop.as_view(), name='drop'),
], 'humanmean')

pship_urlpatterns = ([
    url(_(r'^add/$'),
        PartnershipAdd.as_view(), name='add'),
    url(_(r'^(?P<pship_pk>\d+)/edit/$'),
        PartnershipEdit.as_view(), name='edit'),
    url(_(r'^(?P<pship_pk>\d+)/drop/$'),
        PartnershipDrop.as_view(), name='drop'),
], 'partnership')

result_urlpatterns = ([
    url(_(r'^add/$'),
        ResultAdd.as_view(), name='add'),
    url(_(r'^(?P<result_pk>\d+)/edit/$'),
        ResultEdit.as_view(), name='edit'),
    url(_(r'^(?P<result_pk>\d+)/drop/$'),
        ResultDrop.as_view(), name='drop'),
], 'result')

step_urlpatterns = ([
    url(_(r'^add/$'),
        StepAdd.as_view(), name='add'),
    url(_(r'^(?P<step_pk>\d+)/edit/$'),
        StepEdit.as_view(), name='edit'),
    url(_(r'^(?P<step_pk>\d+)/drop/$'),
        StepDrop.as_view(), name='drop'),
], 'step')

state_urlpatterns = ([
    url(_(r'^add/\?type_id=(?P<type_id>\d+)/$'),
        StateAdd.as_view(), name='add'),
    url(_(r'^(?P<state_pk>\d+)/see/$'),
        StateSee.as_view(), name='see'),
    url(_(r'^(?P<state_pk>\d+)/edit/$'),
        StateEdit.as_view(), name='edit'),
    url(_(r'^(?P<state_pk>\d+)/techfile/$'),
        StateTechFile.as_view(), name='techfile'),
    url(_(r'^(?P<state_pk>\d+)/export/$'),
        StateExport.as_view(), name='export'),
    # url(_(r'^(?P<state_pk>\d+)/exportpdf/$'),
    #     StateExportPdf, name='exportpdf'),
    url(_(r'^(?P<state_pk>\d+)/accountline/'),
        include(aline_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/extension/'),
        include(extension_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/funding/'),
        include(funding_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/humanmean/'),
        include(hmean_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/partnership/'),
        include(pship_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/result/'),
        include(result_urlpatterns)),
    url(_(r'^(?P<state_pk>\d+)/step/'),
        include(step_urlpatterns)),
], 'state')

indicator_urlpatterns = ([
    url(_(r'^add/$'),
        IndicatorAdd.as_view(), name='add'),
    url(_(r'^(?P<indi_pk>\d+)/edit/$'),
        IndicatorEdit.as_view(), name='edit'),
    url(_(r'^(?P<indi_pk>\d+)/drop/$'),
        IndicatorDrop.as_view(), name='drop'),
], 'indi')

identity_urlpatterns = ([
    url(_(r'^add/$'),
        IdentityAdd.as_view(), name='add'),
    url(_(r'^(?P<iden_pk>\d+)/edit/$'),
        IdentityEdit.as_view(), name='edit'),
    url(_(r'^(?P<iden_pk>\d+)/indicator/'),
        include(indicator_urlpatterns)),
    url(_(r'^(?P<iden_pk>\d+)/state/'),
        include(state_urlpatterns)),
], 'iden')

urlpatterns = [
    url(_(r'^(?P<node_pk>\d+)/add/$'),
        NodeAdd.as_view(), name='add'),
    url(_(r'^(?P<node_pk>\d+)/see/$'),
        NodeSee.as_view(), name='see'),
    url(_(r'^(?P<node_pk>\d+)/edit/$'),
        NodeEdit.as_view(), name='edit'),
    url(_(r'^(?P<node_pk>\d+)/identity/'),
        include(identity_urlpatterns)),
]

state/models.py
# ope -- stands for "Outil de Préparation à l'Évaluation" in french
# Copyright 2015 ope contributors.  See AUTHORS.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
Describes the dynamic informations of operation related to the park.
A dynamic information evolves during an operation.
"""

from django.db import \
    models
from django.db.models import \
    Sum
from django.urls import \
    reverse
from django.utils.translation import \
    ugettext_lazy as _
from django.utils.text import \
    slugify
from identity.models import \
    Identity, \
    Indicator
from job.models import \
    History
from partner.models import \
    Partner


class StateType(models.Model):

    """
    A state type represents the nature of a state:
    prévision, réalisation.
    """

    label = models.CharField(
        max_length=25,
        unique=True,
        verbose_name=_('label'),
        help_text=_(
            'Unique name of the nature of state.'))

    class Meta:
        verbose_name = _('state type')
        verbose_name_plural = _('state types')

    def __str__(self):
        return self.label


class State(models.Model):

    """
    A state gathers the dynamic informations of an operation.
    """

    identity = models.ForeignKey(
        Identity,
        verbose_name=_('node'),
        help_text=_(
            'Operation concerned by this dynamic informations.'),
        on_delete=models.CASCADE)

    type = models.ForeignKey(
        StateType,
        verbose_name=_('type'),
        help_text=_(
            'Nature of the operation state.'),
        on_delete=models.CASCADE)

    context = models.CharField(
        max_length=5000,
        verbose_name=_('context and reason'),
        help_text=_(
            'Context and reasons which justify the operation.'))

    description = models.CharField(
        max_length=5000,
        verbose_name=_('description and content'),
        help_text=_(
            'As opposed to long-term purpose, the content represents '
            'a description of the goal which is targetted during the '
            'time of the operation.'))

    locked = models.BooleanField(
        default=False,
        verbose_name=_('locked'),
        help_text=_(
            'Indicates that editing the state is not allowed.'))

    last_update = models.DateTimeField(
        auto_now=True,
        verbose_name=_('last update'),
        help_text=_(
            'Indicates the last time the state was updated.'))

    class Meta:
        verbose_name = _('state')
        verbose_name_plural = _('states')

    def __str__(self):
        result = \
            self.last_update.strftime('%d/%m/%Y') + ' : ' + \
            str(self.type) + ' ' + \
            self.identity.node.short_str()
        return result

    def get_absolute_url(self):
        return reverse('node:iden:state:see',
                       kwargs={'node_pk': self.identity.node.id,
                               'iden_pk': self.identity.id,
                               'state_pk': self.id})

    def get_operation_manager(self):
        partnerships = self.partnership_set.filter(type=10)
        return partnerships

    def get_accountlines_sum(self, al_type):
        accountlines = self.accountline_set.filter(type=al_type)
        result = accountlines.aggregate(Sum('amount'))['amount__sum']
        return result

    def get_expenses_sum(self):
        return self.get_accountlines_sum(al_type=AccountLine.EXPENSE)

    def get_incomes_sum(self):
        return self.get_accountlines_sum(al_type=AccountLine.INCOME)

    def get_distinct_partners(self):
        partnerships = \
            self.partnership_set.order_by().values('partner__name')
        distinct_partners = \
            partnerships.distinct().order_by('partner__name')
        return distinct_partners

    def get_humanmeans_sum(self):
        humanmeans = self.humanmean_set
        sum_aggregate = humanmeans.aggregate(Sum('full_time_days_nb'))
        result = sum_aggregate['full_time_days_nb__sum']
        return result


class Result(models.Model):

    """
    A quantified result represents a measure corresponding to an indicator.
    """

    label = models.CharField(
        max_length=225,
        verbose_name=_('quantified result'),
        help_text=_(
            'A quantified result corresponds to the measure of an '
            'indicator.'))

    state = models.ForeignKey(
        State,
        verbose_name=_('state'),
        help_text=_(
            'Operation concerned by this quantified result.'),
        on_delete=models.CASCADE)

    indicator = models.ForeignKey(
        Indicator,
        verbose_name=_('indicator'),
        help_text=_(
            'Indicator concerned by this quantified result.'),
        on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('result')
        verbose_name_plural = _('results')
        unique_together = (("state", "indicator"),)

    def __str__(self):
        return self.label + ' : ' + str(self.indicator)

    def get_absolute_url(self):
        return reverse('node:iden:state:see',
                       kwargs={'node_pk': self.state.identity.node.id,
                               'iden_pk': self.state.identity.id,
                               'state_pk': self.state.id}) + \
               '#' + str(slugify(self._meta.verbose_name_plural))


class Step(models.Model):

    """
    The steps are time slots that divide an operation.
    """

    label = models.CharField(
        max_length=100,
        verbose_name=_('label'))

    state = models.ForeignKey(
        State,
        verbose_name=_('state'),
        help_text=_('The operation concerned by this step.'),
        on_delete=models.CASCADE)

    start = models.DateField(
        verbose_name=_('start date'),
        help_text=_('The start date must not be empty.'))

    end = models.DateField(
        verbose_name=_('end date'),
        help_text=_('The end date must not be empty.'))

    class Meta:
        verbose_name = _('step')
        verbose_name_plural = _('steps')
        unique_together = (("state", "label"),)
        ordering = ['state__id', 'start', 'end']

    def __str__(self):
        date_format = '%d/%m/%y'  # locale.nl_langinfo(locale.D_FMT)
        result = \
            self.start.strftime(date_format) + ' - ' + \
            self.end.strftime(date_format) + ' : ' + \
            self.label
        return result

    def get_absolute_url(self):
        return reverse('node:iden:state:see',
                       kwargs={'node_pk': self.state.identity.node.id,
                               'iden_pk': self.state.identity.id,
                               'state_pk': self.state.id}) + \
               '#' + str(slugify(self._meta.verbose_name_plural))


class AccountLine(models.Model):

    """
    The account lines allow to detail operation account.
    """

    INCOME = True
    EXPENSE = False
    TYPES = (
        (INCOME, _('income')),
        (EXPENSE, _('expense')))

    label = models.CharField(
        max_length=100,
        verbose_name=_('label'))

    type = models.BooleanField(
        choices=TYPES,
        default=EXPENSE,
        verbose_name=_('expense or income'))

    amount = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        verbose_name=_('amount'),
        help_text=_('The amount in €uros.'))

    state = models.ForeignKey(
        State,
        verbose_name=_('state'),
        on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('account line')
        verbose_name_plural = _('account lines')
        unique_together = (("state", "label"),)
        ordering = ['type']

    def __str__(self):
        if self.type == self.INCOME:
            result = _('income')
        else:
            result = _('expense')
        result += ' ' + str(self.amount) + '€ : ' + self.label
        return result

    def get_absolute_url(self):
        return reverse('node:iden:state:see',
                       kwargs={'node_pk': self.state.identity.node.id,
                               'iden_pk': self.state.identity.id,
                               'state_pk': self.state.id}) + \
               '#' + str(slugify(self._meta.verbose_name_plural))

    def get_rate(self):
        total = self.state.get_accountlines_sum(al_type=self.type)
        rate = round(self.amount / total * 100, 2)
        return rate


class Locality(models.Model):

    """
    A locality is an area where the park leads its operations.
    """

    label = models.CharField(
        max_length=100,
        unique=True,
        verbose_name=_('label'),
        help_text=_(
            'The label is a name which is unique among locality names.'))

    class Meta:
        verbose_name = _('locality')
        verbose_name_plural = _('localities')
        ordering = ['label']

    def __str__(self):
        return self.label

    # def get_absolute_url(self):
    #     return reverse('procedure:list')


class Extension(models.Model):

    """
    An extension prolongs an operation on a locality.
    """

    state = models.ForeignKey(
        State,
        verbose_name=_('state'),
        on_delete=models.CASCADE)
    locality = models.ForeignKey(
        Locality,
        verbose_name=_('locality'),
        on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('extension')

state/templates/state/pane.html
{% load i18n %}
{% load utils_filters %}
          <div class="list-group">
          {% if not object.locked %}
            <a href="{% url res object.identity.node.id object.identity.id object.id %}"
               class="list-group-item">
              <span class="glyphicon glyphicon-plus"
                    aria-hidden="true">
              </span>
              {% trans "add"|capfirst %}
            </a>
          {% endif %}
          {% for row in qset %}
            <li class="list-group-item">
              {{ row }}
            {% if not object.locked %}
              <div class="pull-right">
                {% url row|edit_url row.state.identity.node.id row.state.identity.id row.state.id row.id as edit_url %}
                <a href="{{ edit_url }}"
                   data-toggle="tooltip"
                   title={% trans "edit"|capfirst %}>
                  <span class="glyphicon glyphicon-pencil"
                        aria-hidden="true">
                  </span>
                </a>
                {% url row|drop_url row.state.identity.node.id row.state.identity.id row.state.id row.id as drop_url %}
                <a href="{{ drop_url }}"
                   data-toggle="tooltip"
                   title={% trans "drop"|capfirst %}>
                  <span class="glyphicon glyphicon-remove"
                        aria-hidden="true">
                  </span>
                </a>
              </div>
            {% endif %}
            </li>
          {% endfor %}
          </div>

state/templates/state/state_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ object.identity.node.short_str }}{% endblock %}

{% block bar %}
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle"
               data-toggle="dropdown" role="button"
               aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-export"
                    aria-hidden="true"></span>
              {% trans "export"|capfirst %} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="{% url 'node:iden:state:techfile' object.identity.node.id object.identity.id object.id %}">
                  <span class="glyphicon glyphicon-export"
                        aria-hidden="true"></span>
                  {% trans "technical file"|capfirst %}
                </a>
              </li>
              <li>
                <a href="{% url 'node:iden:state:export' object.identity.node.id object.identity.id object.id %}">
                  <span class="glyphicon glyphicon-export"
                        aria-hidden="true"></span>
                  {% trans "state"|capfirst %} {{ object.type }}
                </a>
              </li>
            </ul>
          </li>
        </ul>
{% endblock %}

{% block content %}
  {% trans "state"|capfirst as trans_state %}
  {% trans "edit"|capfirst as trans_edit %}
  {% include "top.html" with h2=object.identity.node small=trans_state %}
  {% include "tree/node_ancestors.html" with node=object.identity.node %}
    <div>
      <h3>{{ trans_state }} <small>{{ object.type }}</small></h3>
      <p><strong>{% trans "context"|capfirst %}</strong></p>
      <p class="text-justify">{{ object.context|linebreaksbr }}
      {% if not object.locked %}
        <a href="{% url 'node:iden:state:edit' object.identity.node.id object.identity.id object.id %}"
           data-toggle="tooltip"
           title={{ trans_edit }}>
          <span class="glyphicon glyphicon-pencil"
                aria-hidden="true"></span>
        </a>
      {% endif %}
      </p>
      <p><strong>{% trans "description"|capfirst %}</strong></p>
      <p class="text-justify">{{ object.description|linebreaksbr }}
      {% if not object.locked %}
        <a href="{% url 'node:iden:state:edit' object.identity.node.id object.identity.id object.id %}"
           data-toggle="tooltip"
           title={{ trans_edit }}>
          <span class="glyphicon glyphicon-pencil"
                aria-hidden="true"></span>
        </a>
      {% endif %}
      </p>
      <p id="{% trans "fundings"|slugify %}">
        <strong>{% trans "procedures"|capfirst %}</strong>
        <!--span class="badge"-->
        <span class="label label-default">
          {{ object.funding_set.count }}
        </span>
      </p>
          {% include "state/pane.html" with res='node:iden:state:funding:add' qset=object.funding_set.all %}
      <p id="{% trans "steps"|slugify %}">
        <strong>{% trans "steps"|capfirst %}</strong>
        <!--span class="badge"-->
        <span class="label label-default">
          {{ object.step_set.count }}
        </span>
      </p>
          {% include "state/pane.html" with res='node:iden:state:step:add' qset=object.step_set.all %}
      <p id="{% trans "results"|slugify %}">
        <strong>{% trans "results"|capfirst %}</strong>
        <!--span class="badge"-->
        <span class="label label-default">
          {{ object.result_set.count }}
        </span>
      </p>
          {% include "state/pane.html" with res='node:iden:state:result:add' qset=object.result_set.all %}
      <p id="{% trans "partnerships"|slugify %}">
        <strong>{% trans "partnerships"|capfirst %}</strong>
        <!--span class="badge"-->
        <span class="label label-default">
          {{ object.partnership_set.count }}
        </span>
      </p>
          {% include "state/pane.html" with res='node:iden:state:partnership:add' qset=object.partnership_set.all %}
      <p id="{% trans "human means"|slugify %}">
        <strong>{% trans "human means"|capfirst %}</strong>
        <!--span class="badge"-->
        <span class="label label-default">
          {{ object.humanmean_set.count }}
        </span>
      </p>
          {% include "state/pane.html" with res='node:iden:state:humanmean:add' qset=object.humanmean_set.all %}
      <p id="{% trans "account lines"|slugify %}">
        <strong>{% trans "account lines"|capfirst %}</strong>
        <!--span class="badge"-->
        <span class="label label-default">
          {{ object.accountline_set.count }}
        </span>
      </p>
          {% include "state/pane.html" with res='node:iden:state:accountline:add' qset=object.accountline_set.all %}
      <p id="{% trans "extensions"|slugify %}">
        <strong>{% trans "localities"|capfirst %}</strong>
        <!--span class="badge"-->
        <span class="label label-default">
          {{ object.extension_set.count }}
        </span>
      </p>
          {% include "state/pane.html" with res='node:iden:state:extension:add' qset=object.extension_set.all %}
    </div>{% endblock %}

state/templates/state/state_export.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>{{ object.identity.node.short_str }}</title>
  <link rel="stylesheet"
        type="text/css"
        href="{% static "css/state_tech_file.css" %}">
</head>
<!--body contenteditable="true"-->
<body>
    <div class="content">
      <h3>
        {% trans "state"|capfirst %}
        {{ object.type }}
        {{ object.identity.node.type }} :<br />
        {{ object.identity.node }}
      </h3>
      <div class="section">
        <h4>Lien avec la Charte</h4>
        <ul>
        {% for ancestor in object.identity.node.get_ancestors %}
          <li>{{ ancestor.type }} {{ ancestor }}
          {% if ancestor.type.id == 3 %}
          <p>{{ ancestor.identity.purpose|linebreaksbr }}</p>
          {% endif %}
          </li>
        {% endfor %}
        </ul>
      </div>
      <div class="section">
        <h4>{% trans "label"|capfirst %}</h4>
        <p>
        {% if object.identity.label %}{{ object.identity.label }}
        {% else %}{{ object.identity.node }}
        {% endif %}
        </p>
      </div>
      <div class="section">
        <h4>{% trans "anteriority"|capfirst %}</h4>
        <p>{{ object.identity.anteriority|linebreaksbr }}</p>
      </div>
      <div class="section">
        <h4>{% trans "long-term purpose"|capfirst %}</h4>
        <p>{{ object.identity.purpose|linebreaksbr }}</p>
      </div>
      <div class="section">
        <h4>{% trans "context"|capfirst %}</h4>
        <p>{{ object.context|linebreaksbr }}</p>
      </div>
      <div class="section">
        <h4>{% trans "description"|capfirst %}</h4>
        <p>{{ object.description|linebreaksbr }}</p>
      </div>
      <div class="section">
        <h4>{% trans "procedures"|capfirst %}</h4>
        <ul>
        {% for funding in object.funding_set.all %}
          <li>{{ funding }}</li>
        {% endfor %}
        </ul>
      </div>
      <div class="section">
        <h4>Calendrier</h4>
        <ul>
        {% for step in object.step_set.all %}
          <li>{{ step }}</li>
        {% endfor %}
        </ul>
      </div>
      <div class="section">
        <h4>{% trans "indicators"|capfirst %} &
            {% trans "results"|capfirst %}</h4>
        <ul>
        {% for result in object.result_set.all %}
          <li>{{ result }}</li>
        {% endfor %}
        </ul>
      </div>
      <div class="section">
        <h4>{% trans "partners"|capfirst %}</h4>
        <ul>
        {% for partner in object.get_distinct_partners %}
          <li>{{ partner.partner__name }}</li>
        {% endfor %}
        </ul>
      </div>
      <div class="section">
        <h4>{% trans "human means"|capfirst %}</h4>
        <table>
          <thead>
            <tr>
              <th>{% trans "human mean type"|capfirst %}</th>
              <th>{% trans "job"|capfirst %}</th>
              <th>{% trans "job type"|capfirst %}</th>
              <th>{% trans "person"|capfirst %}</th>
              <th>{% trans "full time days number"|capfirst %}</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <th>{% trans "total"|capfirst %}</th>
              <td class="amount">{{ object.get_humanmeans_sum }}</td>
            </tr>
          </tfoot>
          {% for humanmean in object.humanmean_set.all %}
          <tr>
            <td>{{ humanmean.type }}</td>
            <td>{{ humanmean.history.job }}</td>
            <td>{{ humanmean.history.type }}</td>
            <td>{{ humanmean.history.person }}</td>
            <td class="amount">{{ humanmean.full_time_days_nb }}</td>
          </tr>
          {% endfor %}
        </table>
      </div>
      <div class="section">
        <h4>Plan de financement (hors taxes)</h4>
        <table>
          <thead>
            <tr>
              <th>{% trans "label"|capfirst %}</th>
              <th>{% trans "expense"|capfirst %} (€ HT)</th>
              <th>Taux (%)</th>
              <th>{% trans "label"|capfirst %}</th>
              <th>{% trans "income"|capfirst %} (€ HT)</th>
              <th>Taux (%)</th>
            </tr>
          </thead>
        {% for accountline in object.accountline_set.all %}
          <tr>
            {% if accountline.type %}
            <td class="lbl"></td>
            <td class="amount"></td>
            <td class="amount"></td>
            {% endif %}
            <td class="lbl">{{ accountline.label }}</td>
            <td class="amount">{{ accountline.amount }}</td>
            <td class="amount">{{ accountline.get_rate }}</td>
            {% if not accountline.type %}
            <td class="lbl"></td>
            <td class="amount"></td>
            <td class="amount"></td>
            {% endif %}
          </tr>
        {% endfor %}
          <tfoot>
            <tr>
              <th>{% trans "total"|capfirst %}</th>
              <td class="amount">{{ object.get_expenses_sum }}</td>
              <td></td>
              <th>{% trans "total"|capfirst %}</th>
              <td class="amount">{{ object.get_incomes_sum }}</td>
              <td></td>
            </tr>
          </tfoot>
        </table>
      </div>
      <div class="section">
        <h4>{% trans "localities"|capfirst %}</h4>
        <ul>
        {% for locality in object.extension_set.all %}
          <li>{{ locality }}</li>
        {% endfor %}
        </ul>
      </div>
    </div>
  <div id="print-foot"></div>
</body>
</html>